# Generated by Django 4.2.4 on 2023-08-12 18:09

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_studentuser_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_department', to='account.department'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_faculty', to='account.faculty'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=account.models.StudentUser.profile_picture_upload_path),
        ),
    ]
