# Generated by Django 4.2.4 on 2023-08-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_screenuser_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenuser',
            name='student',
        ),
        migrations.AddField(
            model_name='screenuser',
            name='students',
            field=models.ManyToManyField(to='account.studentuser'),
        ),
    ]
