# Generated by Django 4.2.4 on 2023-08-12 18:17

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_studentuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daouser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dao_department', to='account.department'),
        ),
        migrations.AlterField(
            model_name='saouser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sao_faculty', to='account.faculty'),
        ),
        migrations.AlterField(
            model_name='screenuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_department', to='account.department'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=account.models.StudentUser.profile_picture_upload_path),
        ),
    ]
