# Generated by Django 4.2.4 on 2023-08-12 18:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_daouser_department_alter_saouser_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=account.models.StudentUser.profile_picture_upload_path),
        ),
    ]
