# Generated by Django 4.2.4 on 2023-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_studentuser_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
