# Generated by Django 4.2.4 on 2023-08-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_studentuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daouser',
            options={'verbose_name_plural': 'DAOUsers'},
        ),
        migrations.AlterModelOptions(
            name='saouser',
            options={'verbose_name_plural': 'SAOUsers'},
        ),
        migrations.AlterModelOptions(
            name='screenuser',
            options={'verbose_name_plural': 'ScreenUsers'},
        ),
        migrations.AlterModelOptions(
            name='senateuser',
            options={'verbose_name_plural': 'SenateUsers'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name_plural': 'StudentUsers'},
        ),
        migrations.AlterModelOptions(
            name='uaouser',
            options={'verbose_name_plural': 'UAOUsers'},
        ),
    ]
