# Generated by Django 4.2.4 on 2023-08-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_studentuser_next_of_kin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20),
        ),
    ]
