# Generated by Django 4.2.4 on 2023-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_studentuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='user_type',
            field=models.CharField(choices=[('DAO', 'DAO'), ('SAO', 'SAO'), ('SENATE', 'SENATE'), ('SCREEN', 'SCREEN'), ('STUDENT', 'STUDENT'), ('UAO', 'UAO')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
