# Generated by Django 4.2.4 on 2023-08-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.AddField(
            model_name='faculty',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, to='account.department'),
        ),
    ]
