# Generated by Django 4.2.4 on 2023-08-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_faculty_department_faculty_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenuser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_department', to='account.faculty'),
        ),
    ]
