# Generated by Django 4.2.4 on 2023-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_screenuser_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='departments',
            field=models.ManyToManyField(to='account.department'),
        ),
    ]
