# Generated by Django 4.2.4 on 2023-08-18 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_1', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('form_04', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('form_09', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('form_08', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('form_12', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('form_13', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('submitted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocumentICT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamb_admission_letter', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('futo_post_ume_result', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('o_level_result', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('confirmation_of_admission', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('futo_admission_letter', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('validity_form', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('acceptance_letter', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('lga_identification', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('school_fees_receipt', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('direct_entry_result', models.FileField(blank=True, null=True, upload_to=document.models.student_document_upload_path, validators=[document.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only PDF, PNG, JPEG, and JPG files are allowed.')])),
                ('submitted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='accounts.studentuser')),
            ],
        ),
    ]
