# Generated by Django 4.2.4 on 2023-08-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='acceptance_letter',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='birth_certificate',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='confirmation_of_admission',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='direct_entry_result',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='futo_admission_letter',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='futo_post_ume_result',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='lga_identification',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='o_level_result',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='school_fees_receipt',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='validity_form',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='jamb_admission_letter',
            field=models.FileField(upload_to='student_documents/student'),
        ),
    ]
