# Generated by Django 4.2.4 on 2023-08-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_daouser_students_saouser_students_and_more'),
        ('document', '0003_alter_studentdocument_direct_entry_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDocument',
            new_name='StudentDocumentICT',
        ),
    ]
