# Generated by Django 4.2.4 on 2023-08-13 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_daouser_students_saouser_students_and_more'),
        ('document', '0004_rename_studentdocument_studentdocumentict'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocumentict',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdocumentict',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_1', models.TextField(blank=True, null=True)),
                ('form_04', models.TextField(blank=True, null=True)),
                ('form_09', models.TextField(blank=True, null=True)),
                ('form_08', models.TextField(blank=True, null=True)),
                ('form_12', models.TextField(blank=True, null=True)),
                ('form_13', models.TextField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('ictdocs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ictdocss', to='document.studentdocumentict')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_final', to='account.studentuser')),
            ],
        ),
    ]
