# Generated by Django 4.2.4 on 2023-08-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_studentdocumentict_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='form_04',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_08',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_09',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_1',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_12',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_13',
            field=models.FileField(default=1, upload_to='student_documents/student'),
            preserve_default=False,
        ),
    ]
