# Generated by Django 4.2.4 on 2023-08-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_studentrecord_form_04_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocumentict',
            name='acceptance_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='confirmation_of_admission',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='futo_admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='futo_post_ume_result',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='jamb_admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='lga_identification',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='o_level_result',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='school_fees_receipt',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentdocumentict',
            name='validity_form',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_04',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_08',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_09',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_1',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_12',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='form_13',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/student'),
        ),
    ]
